// Generated by scripts/configure.mjs; edit project.config.json instead.
export const SOURCE_URL = "https://github.com/muyu88/mywloc/tree/main";
export const MODULE_LINKS = [
  {
    "name": "Surge / Egern",
    "url": "https://raw.githubusercontent.com/muyu88/mywloc/refs/heads/main/modules/wloc.sgmodule"
  },
  {
    "name": "Quantumult X",
    "url": "https://raw.githubusercontent.com/muyu88/mywloc/refs/heads/main/modules/wloc.conf"
  },
  {
    "name": "Loon",
    "url": "https://raw.githubusercontent.com/muyu88/mywloc/refs/heads/main/modules/wloc.lpx"
  },
  {
    "name": "Stash",
    "url": "https://raw.githubusercontent.com/muyu88/mywloc/refs/heads/main/modules/wloc.stoverride"
  },
  {
    "name": "Shadowrocket",
    "url": "https://raw.githubusercontent.com/muyu88/mywloc/refs/heads/main/modules/wloc.module"
  }
];
