import { readFile, writeFile, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
export async function generatedFiles() {
  const config = JSON.parse(await readFile(path.join(root, 'project.config.json'), 'utf8'));
  if (!/^[A-Za-z0-9_-]+\/[A-Za-z0-9_.-]+$/.test(config.repository)) throw new Error('repository 必须是 owner/repo');
  if (!/^[A-Za-z0-9_.-]+$/.test(config.branch)) throw new Error('branch 仅支持字母、数字、点、下划线和连字符');
  if (config.siteUrl) {
    const url = new URL(config.siteUrl);
    if (url.protocol !== 'https:' || url.username || url.password || url.search || url.hash || url.pathname !== '/') {
      throw new Error('siteUrl 必须是 HTTPS 站点根地址，不含凭据、查询或片段');
    }
  }
  const repoUrl = `https://github.com/${config.repository}`;
  const rawUrl = `https://raw.githubusercontent.com/${config.repository}/refs/heads/${config.branch}`;
  const files = new Map();
  for (const name of await readdir(path.join(root, 'templates/modules'))) {
    const template = (await readFile(path.join(root, 'templates/modules', name), 'utf8')).replaceAll('\r\n', '\n');
    files.set(`modules/${name}`, template.replaceAll('{{REPO_URL}}', repoUrl)
      .replaceAll('{{RAW_URL}}', rawUrl)
      .replaceAll('{{OPEN_URL_LINE}}', config.siteUrl ? `#!openUrl=${new URL(config.siteUrl).origin}/` : ''));
  }
  const readme = (await readFile(path.join(root, 'README.md'), 'utf8')).replaceAll('\r\n', '\n');
  const rows = [['Surge / Egern', 'sgmodule'], ['Quantumult X', 'conf'], ['Loon', 'lpx'], ['Stash', 'stoverride'], ['Shadowrocket', 'module']];
  const modules = rows.map(([name, ext]) => ({ name, url: `${rawUrl}/modules/wloc.${ext}` }));
  const subscriptions = [
    '<!-- subscriptions:start -->',
    '| 客户端 | 订阅地址 |', '| --- | --- |',
    ...modules.map(({ name, url }) => `| ${name} | [${url}](${url}) |`),
    '', config.siteUrl ? `选点页面：[${new URL(config.siteUrl).origin}/](${new URL(config.siteUrl).origin}/)。` : '选点页面：尚未配置公共实例，请按下方说明自行部署。',
    '', `[浏览源码](${repoUrl}) · [部署到 Cloudflare Workers](https://deploy.workers.cloudflare.com/?url=${repoUrl}/tree/${config.branch}/worker)`,
    '<!-- subscriptions:end -->',
  ].join('\n');
  if (!readme.includes('<!-- subscriptions:start -->') || !readme.includes('<!-- subscriptions:end -->')) throw new Error('README 缺少订阅区标记');
  files.set('README.md', readme.replace(/<!-- subscriptions:start -->[\s\S]*?<!-- subscriptions:end -->/, subscriptions));
  files.set('worker/src/project.js', `// Generated by scripts/configure.mjs; edit project.config.json instead.\nexport const SOURCE_URL = ${JSON.stringify(`${repoUrl}/tree/${config.branch}`)};\nexport const MODULE_LINKS = ${JSON.stringify(modules, null, 2)};\n`);
  return { config, files };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { files } = await generatedFiles();
  for (const [name, content] of files) await writeFile(path.join(root, name), content);
  console.log(`已更新 ${files.size} 个文件；发布前运行 npm run check:release。`);
}
